name: Push commit

on: push

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          ref: ${{ github.event.push.head.ref }}

      - name: Check diff
        shell: bash
        run: |
          echo ::set-env name=DIF::`git diff HEAD HEAD~1 --name-only | egrep [0-9]+\/`

      - name: Commit and Push changes
        if: ${{ env.DIF }}
        env:
          DIF: ${{ env.DIF }}
        run: |
          MSG=`git log -1 --pretty=%B | head -1 | awk '{print "|" strftime("%Y/%m/%d") "|" $0 "|" }'`
          git config --global user.name 'Joona Yoon'
          git config --global user.email 'joonas-yoon@users.noreply.github.com'
          echo $MSG >> READMD.md
          git add README.md
          git commit -m "Automated changes:\n${DIF}"
          git push
