name: Push commit

on: push

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          ref: ${{ github.event.push.head.ref }}

      - name: Check diff
        run: |
          MSG=`git diff ${GITHUB_REF##*/} ${GITHUB_REF##*/}~1 --name-only | egrep [0-9]+\/`
          if (( $(echo $MSG | wc -l) -n )); then echo ::set-env name=TESTVAR::$MSG; fi

      - name: Test if-condition
        if: ${{ env.TESTVAR }}
        env:
          msg: ${{ env.TESTVAR }}
        run: |
          echo "PASSED IF CONDITION : $msg"
