name: Push commit

on: push

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check diff
        run: |
          if (( $(git diff --name-only HEAD~1 | egrep [0-9]+\/ | wc -l) -n )); then export TESTVAR=1; fi

      - name: Test if-condition
        if: ${{ env.TESTVAR }}
        run: |
          echo "PASSED IF CONDITION"
