name: Push commit

on: push

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          ref: ${{ github.event.push.head.ref }}

      - name: Check diff
        shell: bash
        run: |
          echo ::set-env name=DIF::`git diff HEAD HEAD~1 --name-only | egrep [0-9]+\/` || true
          MSG=`git log -1 --pretty=%B | head -1 | awk '{print "|" strftime("%Y/%m/%d") "|" $0 "|" }'`
          if (( $(echo $DIF | wc -l) -n )); then echo ::set-env name=MSG::$MSG; fi || true

      - name: Commit and Push changes
        if: ${{ env.MSG }}
        env:
          DIF: ${{ env.DIF }}
          MSG: ${{ env.MSG }}
        run: |
          git config --global user.name 'Joona Yoon'
          git config --global user.email 'joonas-yoon@users.noreply.github.com'
          echo $MSG >> READMD.md
          git commit -am "Automated updates\n$DIF"
          git push
